language: java
jdk:
  - oraclejdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vvarela@fi.uba.ar
    on_success: always
    on_failure: always
