@startuml
'https://plantuml.com/state-diagram

scale 350 width
[*] --> VistaPrincipal

state VistaPrincipal {
    VistaPrincipal --> SetearAlgoritmo : drag&drop
}

state SetearAlgoritmo {
    SetearAlgoritmo --> Dibujar : ejecutar
    SetearAlgoritmo --> CrearNuevoBotonPersonalizado : guardar
    SetearAlgoritmo --> VistaPrincipal : cancelar
}

state CrearNuevoBotonPersonalizado{
    CrearNuevoBotonPersonalizado --> Dibujar : Ejecutar
}

state Dibujar{

}

VistaPrincipal --> [*] : salir
@enduml